source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-denysdovhan-SLASH-spaceship-prompt/spaceship.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zpm-zsh-SLASH-colors/colors.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-ael-code-SLASH-zsh-colored-man-pages/colored-man-pages.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions/zsh-completions.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-oldratlee-SLASH-hacker-quotes/hacker-quotes.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-marzocchi-SLASH-zsh-notify/notify.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-hcgraf-SLASH-zsh-sudo/sudo.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-molovo-SLASH-tipz/tipz.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-peterhurford-SLASH-git-aliases.zsh/git-aliases.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-rapgenic-SLASH-zsh-git-complete-urls/zsh-git-complete-urls.plugin.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-desyncr-SLASH-auto-ls/auto-ls.zsh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-b4b4r07-SLASH-enhancd/init.sh
source /home/vivek/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-command-not-found/command-not-found.plugin.zsh
