theme = "solarized-dark"
icons = "awesome"

# [[block]]
# block = "github"
# format = "{total}|{author}|{comment}|{mention}|{review_requested}"

[[block]]
block = "music"
buttons = ["play", "next"]
marquee = false
max_width = 10

[[block]]
block = "nvidia_gpu"
label = "1650"
interval = 1

[[block]]
block = "weather"
service = { name = "openweathermap", api_key = "35e05158b88fdb82f5a0caaa125fe8ed", city_id = "4459467", units = "imperial" }

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "temperature"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}%"
format_swap = "{swap_used_percents}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 5
format = "{percentage} {time} {power}"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"
on_click = "i3-msg 'exec maim -s ~/Pictures/$(date +%s).png'"
